### ISSUE TITLE
KeyError: 'ignore_regexps' when running gitchangelog

### ISSUE THREAD

**Issue by zot24** [vaab/gitchangelog#33] opened 2015-05-29 11:04 UTC
```
Traceback (most recent call last):
  File "/usr/local/bin/gitchangelog", line 9, in <module>
    load_entry_point('gitchangelog==2.2.0', 'console_scripts', 'gitchangelog')()
  File "/usr/local/lib/python2.7/site-packages/gitchangelog.py", line 1029, in main
    ignore_regexps=config['ignore_regexps'],
KeyError: 'ignore_regexps'
```

Why could this be happening? I just `pip install gitchangelog` and then run `gitchangelog` this is my list of pip packages installed

```
ansible (1.6.10)
ecdsa (0.11)
gitchangelog (2.2.0)
Jinja2 (2.7.3)
Mako (1.0.1)
MarkupSafe (0.23)
paramiko (1.15.1)
pip (1.5.6)
pycrypto (2.6.1)
pystache (0.5.4)
PyYAML (3.11)
setuptools (8.0.2)
vboxapi (1.0)
wsgiref (0.1.2)
```

**Comment by drscream** [comment] 2015-05-29 15:48
I run into the same issue. After a little bit of debugging I think it's looking for the configuration file at the wrong place. Also if no configuration file is there it try to load the `gitchangelog.rc.reference`.

I've installed the package via `pip` into an `virtualenv`. The configuration is placed at `~/.virtualenvs/myenv` but the script is looking at `~/.virtualenvs/myenv/lib/python2.7/site-packages`.

With the old setup it also checked for an `~/.gitchangelog.rc` but now it requires the `.gitchangelog.rc` in the project folder. After copying the `gitchangelog.rc.reference` to the correct place the script is working.

**Comment by vaab** [comment] 2015-06-08 05:27
Many thanks for the feedbacks, can you tell me which version of ``pip`` and ``setuptools`` you are using ? Does all this works by forcing setuptools to version ``9.1`` ? or pip to ``1.5.6`` ? I'll do thorough test about this in the following days, I've been quite busy lately, and still am.

**Comment by drscream** [comment] 2015-06-08 05:37
My error could be reproduced with the python and pip version below:
```
Python 2.7.9
pip 7.0.1
```

If I do an upgrade to pip version 7.0.3 i still got the error.

**Comment by zot24** [comment] 2015-06-08 11:08
For me it's seems like I got a very old version of `pip` :worried: 

```
Python 2.7.9
pip 1.5.6
```

I'm going to try updating `pip` to see if that helps.

**Comment by zot24** [comment] 2015-06-08 11:10
Ok! `pip` updated to `7.0.3` same issue here :disappointed:

**Comment by zot24** [comment] 2015-06-08 11:14
Sorry I forgot to mention I got:

```
setuptools 8.0.2
```

**Comment by vaab** [comment] 2015-06-09 08:57
Many thanks for your tests, I believe this is a duplicate of #34 ... can you tell me if new version 2.2.1 is working correctly for you ?

**Comment by zot24** [comment] 2015-06-09 10:41
Just update and test it, this is the error I'm getting:

```
Traceback (most recent call last):
  File "/usr/local/bin/gitchangelog", line 9, in <module>
    load_entry_point('gitchangelog==2.2.1', 'console_scripts', 'gitchangelog')()
  File "/usr/local/lib/python2.7/site-packages/gitchangelog.py", line 1034, in main
    subject_process=config.get("subject_process", noop),
  File "/usr/local/lib/python2.7/site-packages/gitchangelog.py", line 882, in changelog
    for commit in commits:
  File "/usr/local/lib/python2.7/site-packages/gitchangelog.py", line 644, in log
    for key in GIT_FORMAT_KEYS]))
  File "/usr/local/lib/python2.7/site-packages/gitchangelog.py", line 270, in <lambda>
    @itermap(lambda r: r.decode(_preferred_encoding))
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 29: invalid continuation byte
```

It's seems slightly different than the previous error.

**Comment by vaab** [comment] 2015-06-09 13:37
Thanks for your feedback. It seems that now gitchangelog gets installed correctly and your traceback seems unrelated to current issue. 

But it's nonetheless preoccupying. May I ask you to open a new issue with this traceback, and probably expand on telling more about your setup ? (do the test framework passes with no issue on your setup ?). Could you also check that your git log is actually in 'utf-8' ?

If possible, can you give me a link to your git repository so I can pull it ? Or can you create a dummy git repository from scratch that shows the issue ?

Many thanks.

**Comment by zot24** [comment] 2015-06-09 13:46
I'll try to do that as soon as I can and give you the info you need, thanks @vaab

**Closed** 2015-06-09 13:46 UTC

**Comment by skorokithakis** [comment] 2017-01-10 16:40
I'm using 2.4.1 with pip 9.0.1 and am getting the same error. There's no `.gitchangelog.rc` anywhere (not even in the site-packages directory `gitchangelog.py` is in).

**Comment by tuukkamustonen** [comment] 2017-01-10 21:35
@skorokithakis Probably related to https://github.com/vaab/gitchangelog/issues/41.
