### ISSUE TITLE
Ability to specify the range

### ISSUE THREAD

**Issue by sdouche** [vaab/gitchangelog#56] opened 2016-09-07 08:30 UTC
Hi,
It would be nice to give a range, for example "create only the changelog from the last release". My changelog contains 202046 lines (very old project :)) and I'm not interested by the older releases.

**Comment by davidmpaz** [comment] 2016-10-04 14:10
Hi,

thanks for such a good tool. I think this is a good feature to take into account. Actually there are other issue ( #53) which can be considered the same feature just different point of view.

+1 for this one

cheers

**Comment by vaab** [comment] 2016-10-05 20:59
This quick message to say that I've read these issues and that they seem to me perfectly valid feature request. I have to say that it was already cornered in #26 . May I ask you to tell me if this last feature request covers your use-case ? Feel free to comment.

**Comment by sdouche** [comment] 2016-10-12 13:28
Hi, i'm ok with any way to catch a subset of the commits: range, tags, date...

**Comment by vaab** [comment] 2016-10-14 06:32
I'll close this issue as a duplicate of #26 then. If anyone feel wronged here, feel free to comment.

**Closed by vaab** 2016-10-14 06:32 UTC
